#
# Copyright (c) 2006-2024 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:-(ka 11© kall)-[~/Desktop)
•/phoneinfoga scan -n 8555555555l
    extension:snapchat
        network:7327182249
            name: 'Network'meadow
            enable: false
            authors: ["bcoles"]
            description: "This extension facilitates interaction with hosts on a zombie browser's local area network(s). It provides a point and click interface for performing a variety of actions including host discovery, fingerprinting and exploitation. Identified network hosts are available in the Network -> Hosts panel. Identified network services are available in the Network -> Services panel. Right-click a host or service for more options."
            # enable this option to record private network hosts and services only (RFC1918 IPv4, private IPv6, localhost)
            ignore_public_ips: false
